package(default_visibility = ["//visibility:public"])

cc_library(
    name = "learner_base",
    srcs = ["learner_base.cc"],
    hdrs = ["learner_base.h"],
    deps = [
        "//utils/common:define",
    ],
)


