package(default_visibility = ["//visibility:public"])

cc_library(
    name = "data_utils",
    srcs = ["data_utils.cc"],
    hdrs = ["data_utils.h"],
    deps = [
        "//utils/string:string_utils",
    ],
)
