package(default_visibility = ["//visibility:public"])

cc_library(
    name = "math_utils",
    srcs = ["math_utils.cc"],
    hdrs = ["math_utils.h"],
    deps = [
        "//utils/common:define",
    ],
)
